#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Poio Tools for Linguists
#
# Copyright (C) 2009-2013 Poio Project
# Author: Peter Bouda <pbouda@cidles.eu>
# URL: <http://media.cidles.eu/poio/>
# For license information, see LICENSE

import configparser

import pressagio.callback
import pressagio.context_tracker
import pressagio.predictor

# Define and create PresageCallback object
class DemoCallback(pressagio.callback.Callback):
    def __init__(self, buffer):
        super().__init__()
        self.buffer = buffer

    def past_stream(self):
        return self.buffer
    
    def future_stream(self):
        return ''

config_file = "example_profile.ini"
config = configparser.ConfigParser()
config.read(config_file)

predictor_registry = pressagio.predictor.PredictorRegistry(config)

callback = DemoCallback("Des is a Te")
context_tracker = pressagio.context_tracker.ContextTracker(
    config, predictor_registry, callback)

predictor_activator = pressagio.predictor.PredictorActivator(
    config, predictor_registry, context_tracker)
predictor_activator.combination_policy = "meritocracy"

predictions = predictor_activator.predict()
#predictor = predictor_registry[0]
#predictions = predictor.predict(5, None)
for p in predictions:
    print(p.word)
print()

